### ISSUE TITLE
[Meta] Issues with deploying Prisma with Docker

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2189]
There's been a lot of questions about cluster deployment and operating a cluster on Digital Ocean or elsewhere.

Documentation around this topic can be found [here](https://www.prisma.io/docs/reference/clusters/docker-aira9zama5), [here](https://www.prisma.io/docs/tutorials/cluster-deployment/digital-ocean-(docker-machine)-texoo9aemu) and [here](https://www.prisma.io/docs/tutorials/cluster-deployment/digital-ocean-(manual)-texoo6aemu). We'll continue to improve it.

I'm keeping a list of questions here, so we can answer them one by one overtime:

* [ ] https://www.graph.cool/forum/t/upgrading-a-cluster-on-digital-ocean/2378?u=nilan
* [ ] https://www.graph.cool/forum/t/cluster-deployment-fail-to-query-deployed-project-on-remote-self-hosted-cluster/2414?u=nilan
* [ ] https://www.graph.cool/forum/t/how-to-eject-prisma-and-use-docker-compose-yml-to-deploy-prisma-with-other-services-e-g-node-js-server/2392?u=nilan
* [ ] https://www.graph.cool/forum/t/cant-start-prisma-local-cluster-on-virtual-private-server/2149?u=nilan
* [ ] https://www.graph.cool/forum/t/production-ready-prisma-on-aws-eb-ecs-what-are-valid-options/2380?u=nilan
* [ ] https://www.graph.cool/forum/t/fetcherror-request-to-http-localhost-4466-cluster-failed-reason-socket-hang-up/2438?u=nilan
---
* [ ] https://github.com/graphcool/prisma/issues/1779
* [ ] https://github.com/graphcool/prisma/issues/1771

**Comment by marktani** [comment]
Most of the issues are fixed. We will continue to improve the Docker experience.
